### ISSUE TITLE
msg.blob should be named msg.buffers

### ISSUE THREAD

**Issue by rgbkrk** [n-riesco/jmp#14]
[To match the Notebook websockets](https://github.com/jupyter/notebook/blob/23ca9602c2fdd0cd705ec97c2feee909e7865e67/notebook/static/services/kernels/kernel.js#L83)

**Comment by n-riesco** [comment]
I think `buffers` is a bit of a misnomer. But since `jupyter-notebook` and `jupyter-client` use this name, `jmp`'d better do the same.

I guess the messaging spec should also be updated too ([here](https://github.com/jupyter/jupyter_client/blame/d3f58091dfc8495464c112ef8ba12694ef4c505a/docs/messaging.rst#L161) and [here](https://github.com/jupyter/jupyter_client/blame/d3f58091dfc8495464c112ef8ba12694ef4c505a/docs/messaging.rst#L173)).

**Comment by rgbkrk** [comment]
> I think buffers is a bit of a misnomer.

Yeah, I agree. I mostly care about consistency since we have a light abstraction layer that works across the websockets and zmq in enchannel. This was the only field that differed.

I think I'll start out with opening an issue on `jupyter_client` before I make any PRs.
